[[services]]
name = "backend"
source = "backend"
build.builder = "dockerfile"

[services.variables]
PORT = "8000"
PYTHONPATH = "/app"

[[services]]
name = "frontend"
source = "frontend"
build.builder = "dockerfile"

[services.variables]
PORT = "3000"
NEXT_PUBLIC_API_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}" 